gpx-animator/gpx-animator

- pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zdila/gpx-animator/25)
> Making build platform independent closes #24

- src/sk/freemap/gpxAnimator/ui/MainFrame.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zdila/gpx-animator/32)
> Fixing render button label

- pom.xml
- src/sk/freemap/gpxAnimator/GpxContentHandler.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zdila/gpx-animator/48)
> Refactoring to use Java 8 DateTime instead of Joda-Time

- pom.xml
- src/sk/freemap/gpxAnimator/GpxContentHandler.java
Reverts zdila/gpx-animator#48 (to prevent conflicts)
> Revert "Refactoring to use Java 8 DateTime instead of Joda-Time"

- src/main/java/sk/freemap/gpxAnimator/ui/MainFrame.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zdila/gpx-animator/52)
> Asking before overwriting an existing output file

- index.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zdila/gpx-animator/43)
> Adding identifiers to headings #42

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zdila/gpx-animator/55)
> Adding link to a video tutorial

- pom.xml
- src/main/java/sk/freemap/gpxAnimator/Constants.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zdila/gpx-animator/63)
> Bumping version to 1.4-SNAPSHOT

- .gitignore
- CHANGELOG.md
- src/main/java/sk/freemap/gpxAnimator/GpxPoint.java
- src/main/java/sk/freemap/gpxAnimator/Photos.java
- src/main/java/sk/freemap/gpxAnimator/Renderer.java
> Adding coordinates to the animation

- src/main/java/sk/freemap/gpxAnimator/ui/MainFrame.java
Conceived during Hackergarten Basel together with @McPringle.
> 'Open Recent File' menu added. closes #75

- README.md
- pom.xml
- src/test/java/sk/freemap/gpxAnimator/ui/TestDurationSpinnerModel.java
There is no unit testing, would be good to start with that. I added some dummy tests.
> Add Unit Testing to the Maven structure

- src/main/java/sk/freemap/gpxAnimator/ui/GeneralSettingsPanel.java
Signed-off-by: Tod Fitch <tod@fitchfamily.org>
> UI consistency: Make all labels upper case words.

- src/main/java/sk/freemap/gpxAnimator/TileCache.java
Signed-off-by: Tod Fitch <tod@fitchfamily.org>
> Fix issue if no cache path is specified.

- src/main/java/app/gpx_animator/CommandLineConfigurationFactory.java
- src/main/java/app/gpx_animator/Configuration.java
- src/main/java/app/gpx_animator/Help.java
- src/main/java/app/gpx_animator/Position.java
- src/main/java/app/gpx_animator/Renderer.java
- Ensures that --input only command line invocation works
- Adds --information-location and --attribution-location command line
- Fixes crash on trailing newline in attribution string
- Fixes how defaults are printed in --help
- Sets reasonable defaults for anything not cmdline specified
- Improves output logging
Code partly contributed by @RonaldBoer.
Test: "java -jar GpxAnimator.jar --input track.gpx" works
> Ensures simplest command line invocation works

- src/main/java/app/gpx_animator/Renderer.java
Fixes a bad refactor bug, now restoring original functionality.
That said, paint() is in need of cleanup.
> Fixes "white line" bug introduced by predraw track

- src/main/java/app/gpx_animator/core/Help.java
- src/main/java/app/gpx_animator/core/Option.java
- src/main/java/app/gpx_animator/ui/cli/CommandLineConfigurationFactory.java
- src/main/resources/i18n/Messages.properties
- src/main/resources/i18n/Messages_de.properties
This PR seeks to implement issue #334 by adding a `--version` commandline option that prints the program's version and exits the program immediately thereafter.
Let me know what you think. :)
> #334 Add version CLI option.

- CONTRIBUTORS.md
Following [your offer](https://github.com/zdila/gpx-animator/pull/340#issuecomment-804673203) this PR adds myself to the CONTRIBUTORS file.
> Adding myself to the contributors list.

- CONTRIBUTORS.md
- build.gradle
- src/main/java/app/gpx_animator/core/data/Photo.java
- src/main/java/app/gpx_animator/core/renderer/plugins/PhotoPlugin.java
- src/main/java/app/gpx_animator/core/util/RenderUtil.java
- src/test/java/app/gpx_animator/core/renderer/plugins/PhotoPluginTest.java
- src/test/java/app/gpx_animator/core/util/RenderUtilTest.java
> :bug: Use EXIF orientation for photo rendering

- src/main/java/app/gpx_animator/core/renderer/Renderer.java
- src/main/java/app/gpx_animator/core/util/LinearInterpolation.java
> Add linear interpolation

- build.gradle
- src/main/java/app/gpx_animator/core/renderer/plugins/PhotoPlugin.java
- src/main/java/app/gpx_animator/core/util/LinearInterpolation.java
- src/main/java/app/gpx_animator/ui/swing/MarkdownDialog.java
- src/test/java/app/gpx_animator/ui/cli/CommandLineIT.java
Returning `GpxPoint` after interpolation. 
Before: 
https://user-images.githubusercontent.com/2463361/202895296-a8484708-a4b1-440d-a118-280912f12727.mp4
After: 
https://user-images.githubusercontent.com/2463361/202896030-143ba5bd-319e-481a-8f76-a3375869698c.mp4
> Fixed #460: Returning GpxPoint after interpolation

- src/main/java/app/gpx_animator/core/renderer/Renderer.java
Reverts gpx-animator/gpx-animator#457
> Revert PR #453 because it breaks the finish track icon feature

- src/main/java/app/gpx_animator/core/Option.java
- src/main/java/app/gpx_animator/core/configuration/Configuration.java
- src/main/java/app/gpx_animator/core/configuration/TrackConfiguration.java
- src/main/java/app/gpx_animator/core/data/gpx/GpxContentHandler.java
- src/main/java/app/gpx_animator/core/renderer/Renderer.java
- src/main/java/app/gpx_animator/ui/cli/CommandLineConfigurationFactory.java
- src/main/resources/i18n/Messages.properties
- src/main/resources/i18n/Messages_de.properties
Added option processing with several <trk> as several input files
> Resolved #454: Added option for processing multitracks files 

- src/main/java/app/gpx_animator/core/Option.java
- src/main/java/app/gpx_animator/core/configuration/Configuration.java
- src/main/java/app/gpx_animator/core/configuration/TrackConfiguration.java
- src/main/java/app/gpx_animator/core/data/gpx/GpxContentHandler.java
- src/main/java/app/gpx_animator/core/renderer/Renderer.java
- src/main/java/app/gpx_animator/ui/cli/CommandLineConfigurationFactory.java
- src/main/resources/i18n/Messages.properties
- src/main/resources/i18n/Messages_de.properties
Reverts gpx-animator/gpx-animator#458
> Revert PR #454 because it breaks save and load operations

- src/main/java/app/gpx_animator/core/configuration/Configuration.java
- src/main/java/app/gpx_animator/core/renderer/plugins/BackgroundMapPlugin.java
- src/main/java/app/gpx_animator/ui/swing/GeneralSettingsPanel.java
- src/main/resources/i18n/Messages.properties
- src/main/resources/i18n/Messages_de.properties
extend UI by field API-key
parse URL
> add support for API key

- src/main/java/app/gpx_animator/core/Help.java
- src/main/java/app/gpx_animator/ui/cli/CommandLineConfigurationFactory.java
this is for #592 
I reproduced the error and now it accepts the "information" argument on the cli, but i didn't really tested it's functionality.
> add information field to command line options

- build.gradle
add plugin for publish jar file for use gpx-animator as lib.
> #625 add plugin maven-publish for create jar.  

- src/main/java/app/gpx_animator/core/configuration/Configuration.java
- src/test/java/app/gpx_animator/ui/cli/CommandLineConfigurationFactoryTest.java
should i add incrementing numbers to the filename if the output file exists already?
> #415 set output to input file name if no output is given

- src/main/java/app/gpx_animator/ui/cli/CommandLineConfigurationFactory.java
- src/test/java/app/gpx_animator/ui/cli/CommandLineConfigurationFactoryTest.java
for ticket #319 
is the implementation how the ticket was intended?
> multiple input files on cli with one --input

- src/main/java/app/gpx_animator/core/renderer/plugins/PhotoPlugin.java
this is for ticket #376. 
It works with bikeride.gpx and bikeride.jpg 🙂
not sure if the check for the marker beeing in the frameImage is needed
> begin and end animation of photo on marker

- src/main/java/app/gpx_animator/core/renderer/plugins/PhotoPlugin.java
works now with your gpx file from #644
> fix photo marker animation
